FROM simple-service-baseimage

RUN echo "Run build at <BUILD_TIMESTAMP>"

COPY ./pom.xml /source/pom.xml
COPY ./src /source/src
WORKDIR /source

#RUN mvn compiler:compile
RUN mvn -offline compiler:compile