FROM maven:3-jdk-8-slim

COPY ./pom.xml /source/pom.xml
WORKDIR /source

#RUN mvn dependency:go-offline
#RUN mvn compile:testCompile
#RUN mvn dependency:copy-dependencies clean
#RUN mvn -B dependency:resolve dependency:resolve-plugins

RUN mvn install
RUN mvn dependency:go-offline
